name: SimpleSuffixes
main: me.dimpl.SimpleSuffixes.SimpleSuffixes
author: Dimpl
version: 1.5
description: Allows non-op players to set their own prefix/suffix through PEX.
commands:
  suffix:
    description: Allows a player to set their own suffix.
    aliases: [suf]
  prefix:
    description: Allows a player to set their own prefix.
    aliases: [pre]
  suffixr:
    description: Allows someone to reset another player's suffix.
    aliases: [sufr]
  prefixr:
    description: Allows someone to reset another player's prefix.
    aliases: [prer]
  listen:
    description: Toggles listening to another player, emboldening and colouring their chat.
    aliases: [follow]
  listening:
    description: Lists the players being listened to.
    aliases: [following]
  initiate:
    description: Sets a player as initiate.
    aliases: [init]
  initiates:
    description: Lists the players who are initiates.
    aliases: [inits]
permissions:
  simsuf.*:
    default: op
  simsuf.s:
    description: Allows a player to set their own suffix.
  simsuf.p:
    description: Allows a player to set their own prefix.
  simsuf.r:
    description: Allows someone to reset another player's suffix/prefix.
  simsuf.i:
    description: Allows someone to set another player's prefix to initiate.
  simsuf.staff:
    description: Allows someone to use a staff title in their suffix/prefix.